// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Board = (function() {

    Board.COUNT = 0;

    Board.all = [];

    function Board(id, name) {
      this["delete"] = __bind(this["delete"], this);

      this.fetchItems = __bind(this.fetchItems, this);

      this.save = __bind(this.save, this);

      this.content = __bind(this.content, this);

      this.addItem = __bind(this.addItem, this);

      this.setUpView = __bind(this.setUpView, this);
      Board.COUNT++;
      this.lists = [];
      this.input = $('<input type="text"/>');
      this.input.keyup(this.save);
      this.id = ((id != null) ? id : Board.COUNT);
      if ((name != null)) {
        this.input.val(name);
      } else {
        this.input.val("Board");
      }
      this.input.attr('id', "list-" + this.id + "-name");
      this.view = this.setUpView();
      $(".board").append(this.view);
      this.save();
    }

    Board.prototype.setUpView = function() {
      var addItemDiv, listContainer, listDeleteDiv, listItemsDiv, listNameDiv;
      listContainer = $('<div class="list-container"></div>');
      listDeleteDiv = $('<div class="list-delete"><p>x</p></div>');
      listDeleteDiv.click(this["delete"]);
      listNameDiv = $('<div class="list-name"></div>');
      listNameDiv.append(this.input);
      listItemsDiv = $('<div class="list-items"></div>');
      listItemsDiv.attr('id', "list-" + this.id + "-items");
      addItemDiv = $('<div class="add-item">+</div>');
      addItemDiv.click(this.addItem);
      listContainer.append(listDeleteDiv);
      listContainer.append(listNameDiv);
      listContainer.append(listItemsDiv);
      listContainer.append(addItemDiv);
      return listContainer;
    };

    Board.prototype.addItem = function() {
      console.log(this.id);
      return this.items.push(new Item(this.id));
    };

    Board.prototype.content = function() {
      return this.input.val();
    };

    Board.prototype.save = function() {
      var listName;
      listName = this.content();
      return $.post("list.php", {
        'name': listName,
        'id': this.id
      }, function(data) {
        return console.log("Board save data: " + data);
      });
    };

    Board.prototype.fetchItems = function() {
      var _this = this;
      return $.get("item.php", {
        list_id: this.id
      }, function(data) {
        var i, item, _results;
        data = JSON.parse(data);
        _results = [];
        for (i in data) {
          item = data[i];
          _results.push(_this.items.push(new Item(_this.id, item['id'], item['data'])));
        }
        return _results;
      });
    };

    Board.prototype["delete"] = function() {
      if (!confirm("Are you sure?")) {
        return;
      }
      this.view.remove();
      return $.post("list.php", {
        'delete': true,
        'id': this.id
      }, function(data) {
        return console.log("Board save data: " + data);
      });
    };

    Board.init = function() {
      return $.get("list.php", {
        all: "true"
      }, function(data) {
        var i, list, _results;
        data = JSON.parse(data);
        _results = [];
        for (i in data) {
          list = data[i];
          list = new Board(list['id'], list['name']);
          Board.all.push(list);
          _results.push(list.fetchItems());
        }
        return _results;
      });
    };

    return Board;

  })();

}).call(this);
