// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Board = (function() {

    Board.COUNT = 0;

    Board.all = [];

    function Board(id) {
      this.save = __bind(this.save, this);

      this.content = __bind(this.content, this);

      this.addList = __bind(this.addList, this);

      this.setUpView = __bind(this.setUpView, this);

      var name;
      Board.COUNT++;
      this.lists = [];
      this.boardNameView = $('<span type="text" class="board-name"></span>');
      name = prompt("Enter your new Board's name:", "Board");
      this.id = ((id != null) ? id : Board.COUNT);
      if (name) {
        this.boardNameView.text(name);
      } else {
        this.boardNameView.text("Board");
      }
      this.setUpView();
      this.save();
    }

    Board.prototype.setUpView = function() {
      var boardNamesDiv;
      boardNamesDiv = $(".board-names");
      boardNamesDiv.append('<p class="board-name-separator">&nbsp|&nbsp</p>');
      boardNamesDiv.append(this.boardNameView);
      this.view = $('<div class="board"></div>');
      this.view.attr('id', "board-" + this.id);
      return $(".boards").append(this.view);
    };

    Board.prototype.addList = function() {
      return this.lists.push(new List(this.id));
    };

    Board.prototype.content = function() {
      return this.boardNameView.text();
    };

    Board.prototype.save = function() {
      var boardName;
      boardName = this.content();
      return $.post("board.php", {
        'name': boardName,
        'id': this.id
      }, function(data) {
        return console.log("Board save data: " + data);
      });
    };

    Board.init = function() {
      return Board.all.push(new Board());
    };

    return Board;

  })();

}).call(this);
