// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Board = (function() {

    Board.COUNT = 0;

    Board.all = [];

    function Board(id, name) {
      this.makeActive = __bind(this.makeActive, this);

      this.fetchLists = __bind(this.fetchLists, this);

      this.save = __bind(this.save, this);

      this.changeName = __bind(this.changeName, this);

      this.content = __bind(this.content, this);

      this.addList = __bind(this.addList, this);

      this.setUpView = __bind(this.setUpView, this);
      Board.COUNT++;
      this.lists = [];
      this.boardNameView = $('<span type="text" class="board-name"></span>');
      this.id = ((id != null) ? id : Board.COUNT);
      if (!name) {
        name = prompt("Enter your new Board's name:", "Board");
      }
      if (name) {
        this.boardNameView.text(name);
      } else {
        this.boardNameView.text("Board");
      }
      this.setUpView();
      this.save();
    }

    Board.prototype.setUpView = function() {
      var boardNamesDiv;
      boardNamesDiv = $(".board-names");
      boardNamesDiv.append('<p class="board-name-separator">&nbsp|&nbsp</p>');
      boardNamesDiv.append(this.boardNameView);
      this.boardNameView.dblclick(this.changeName);
      this.boardNameView.click(this.makeActive);
      this.view = $('<div class="board"></div>');
      this.view.attr('id', "board-" + this.id);
      return $(".boards").append(this.view);
    };

    Board.prototype.addList = function() {
      return this.lists.push(new List(this.id));
    };

    Board.prototype.content = function() {
      return this.boardNameView.text();
    };

    Board.prototype.changeName = function() {
      var name;
      name = prompt("Enter your Board's new name:", this.content());
      if (name) {
        this.boardNameView.text(name);
        return this.save();
      }
    };

    Board.prototype.save = function() {
      var boardName;
      boardName = this.content();
      return $.post("board.php", {
        'name': boardName,
        'id': this.id
      }, function(data) {
        return console.log("Board save data: " + data);
      });
    };

    Board.prototype.fetchLists = function() {
      var _this = this;
      return $.get("list.php", {
        board_id: this.id,
        all: "true"
      }, function(data) {
        var i, list, _results;
        data = JSON.parse(data);
        _results = [];
        for (i in data) {
          list = data[i];
          list = new List(_this.id, list['id'], list['name']);
          _this.lists.push(list);
          _results.push(list.fetchItems());
        }
        return _results;
      });
    };

    Board.prototype.makeActive = function() {
      var board, _i, _len, _ref;
      _ref = Board.all;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        board = _ref[_i];
        board.view.hide();
        board.boardNameView.removeClass('active');
      }
      this.view.show();
      this.boardNameView.addClass('active');
      return console.log("Board " + this.id + " is now active");
    };

    Board.init = function() {
      return $.get("board.php", {
        all: "true"
      }, function(data) {
        var board, i;
        data = JSON.parse(data);
        for (i in data) {
          board = data[i];
          board = new Board(board['id'], board['name']);
          Board.all.push(board);
          board.fetchLists();
        }
        return Board.all[0].makeActive();
      });
    };

    return Board;

  })();

}).call(this);
