// Generated by CoffeeScript 1.3.3
(function() {

  this.Item = (function() {

    Item.COUNT = 0;

    Item.all = {};

    function Item(id, data) {
      Item.COUNT++;
      this.input = $('<input class="item" type="text"/>');
      this.input.keyup(this.itemChanged);
      switch (arguments.length) {
        case 0:
          this.input.attr('id', "item-" + Item.COUNT);
          $(".list").append(this.input);
          break;
        case 2:
          this.input.attr('id', "item-" + id);
          this.input.val(data);
          $(".list").append(this.input);
      }
    }

    Item.prototype.content = function() {
      return $(this.input).val();
    };

    Item.prototype.save = function() {
      var itemData;
      itemData = this.content();
      return $.post("item.php", {
        data: itemData
      }, function(data) {
        return alert("Data Loaded: " + data);
      });
    };

    Item.prototype.itemChanged = function() {
      var id;
      id = $(this).attr('id').split("-")[1];
      Item.all[id].save();
      return console.log("save called for:" + Item.all[id].content());
    };

    Item.init = function() {
      return $.get("item.php", {
        all: "true"
      }, function(data) {
        var i, item, _results;
        data = JSON.parse(data);
        _results = [];
        for (i in data) {
          item = data[i];
          console.log(item['id'] + '-' + item['data']);
          _results.push(Item.all[item['id']] = new Item(item['id'], item['data']));
        }
        return _results;
      });
    };

    return Item;

  })();

}).call(this);
