// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.List = (function() {

    List.COUNT = 0;

    List.all = [];

    function List(id, name) {
      this.save = __bind(this.save, this);

      this.content = __bind(this.content, this);

      this.setUpView = __bind(this.setUpView, this);

      this.addItem = __bind(this.addItem, this);
      List.COUNT++;
      this.items = [];
      this.input = $('<input type="text"/>');
      this.input.keyup(this.save);
      this.id = ((id != null) ? id : List.COUNT);
      if ((name != null)) {
        this.input.val(name);
      } else {
        this.input.val("List");
      }
      this.input.attr('id', "list-" + this.id + "-name");
      $(".board").append(this.setUpView());
    }

    List.prototype.addItem = function() {
      console.log(this.id);
      return this.items.push(new Item(this.id));
    };

    List.prototype.setUpView = function() {
      var addItemDiv, listContainer, listItemsDiv, listNameDiv;
      listContainer = $('<div class="list-container"></div>');
      listNameDiv = $('<div class="list-name"></div>');
      listNameDiv.append(this.input);
      listItemsDiv = $('<div class="list-items"></div>');
      listItemsDiv.attr('id', "list-" + this.id + "-items");
      addItemDiv = $('<div class="add-item">+</div>');
      addItemDiv.click(this.addItem);
      listContainer.append(listNameDiv);
      listContainer.append(listItemsDiv);
      listContainer.append(addItemDiv);
      return listContainer;
    };

    List.prototype.content = function() {
      return this.input.val();
    };

    List.prototype.save = function() {
      var listName;
      listName = this.content();
      return $.post("list.php", {
        'name': listName,
        'id': this.id
      }, function(data) {
        return console.log("List save data: " + data);
      });
    };

    List.init = function() {
      return $.get("list.php", {
        all: "true"
      }, function(data) {
        var i, list, _results;
        data = JSON.parse(data);
        _results = [];
        for (i in data) {
          list = data[i];
          _results.push(List.all.push(new List(list['id'], list['name'])));
        }
        return _results;
      });
    };

    return List;

  })();

}).call(this);
